### ISSUE TITLE
vs code extension not working on macos

### ISSUE THREAD

**Issue by aditya1944** [vlang/vscode-vlang#390]
[vls_report_1645123809.md](https://github.com/vlang/vscode-vlang/files/8095312/vls_report_1645123809.md)
[vls_report_1645125562.md](https://github.com/vlang/vscode-vlang/files/8095313/vls_report_1645125562.md)
[vls_report_1645171977.md](https://github.com/vlang/vscode-vlang/files/8095314/vls_report_1645171977.md)

**Comment by aditya1944** [comment]
`[Info  - 1:42:22 PM] VLS Version: 0.0.1., OS: macos 64
[Info  - 1:42:22 PM] VLS executable path: /Users/aditya.kumar/.vls/bin/vls
[Info  - 1:42:22 PM] VLS build with V eb45a32
[Info  - 1:42:22 PM] Client / Editor: Visual Studio Code 1.64.2 (PID: 17416)
[Info  - 1:42:22 PM] Using V path (VROOT): /Users/aditya.kumar/Documents/practice/vlang/v
[Info  - 1:43:00 PM] Connection to server got closed. Server will restart.
[Error - 1:43:00 PM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:29:4057)
	at Object.dispose (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:34:9518)
	at Uf.handleConnectionClosed (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:36:9070)
	at Uf.handleConnectionClosed (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:39:12255)
	at n (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:36:8752)
	at Tu.invoke (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:9583)
	at wr.fire (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:10348)
	at it (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:3:10845)
	at Tu.invoke (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:9583)
	at wr.fire (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:10348)
	at Mo.fireClose (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:3:523)
	at Socket.<anonymous> (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:3:1297)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 1:43:00 PM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:29:4057)
	at Object.dispose (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:34:9518)
	at Uf.handleConnectionClosed (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:36:9070)
	at Uf.handleConnectionClosed (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:39:12255)
	at n (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:36:8752)
	at Tu.invoke (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:9583)
	at wr.fire (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:10348)
	at it (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:3:10845)
	at Tu.invoke (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:9583)
	at wr.fire (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:10348)
	at Mo.fireClose (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:3:523)
	at Socket.<anonymous> (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:3:1297)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 1:43:00 PM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:29:4057)
	at Object.dispose (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:34:9518)
	at Uf.handleConnectionClosed (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:36:9070)
	at Uf.handleConnectionClosed (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:39:12255)
	at n (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:36:8752)
	at Tu.invoke (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:9583)
	at wr.fire (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:10348)
	at it (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:3:10845)
	at Tu.invoke (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:9583)
	at wr.fire (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:10348)
	at Mo.fireClose (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:3:523)
	at Socket.<anonymous> (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:3:1297)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 1:43:00 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:29:4057)
	at Object.dispose (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:34:9518)
	at Uf.handleConnectionClosed (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:36:9070)
	at Uf.handleConnectionClosed (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:39:12255)
	at n (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:36:8752)
	at Tu.invoke (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:9583)
	at wr.fire (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:10348)
	at it (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:3:10845)
	at Tu.invoke (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:9583)
	at wr.fire (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:10348)
	at Mo.fireClose (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:3:523)
	at Socket.<anonymous> (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:3:1297)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 1:43:00 PM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:29:4057)
	at Object.dispose (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:34:9518)
	at Uf.handleConnectionClosed (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:36:9070)
	at Uf.handleConnectionClosed (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:39:12255)
	at n (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:36:8752)
	at Tu.invoke (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:9583)
	at wr.fire (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:10348)
	at it (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:3:10845)
	at Tu.invoke (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:9583)
	at wr.fire (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:10348)
	at Mo.fireClose (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:3:523)
	at Socket.<anonymous> (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:3:1297)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 1:43:00 PM] Request textDocument/foldingRange failed.
Error: Connection got disposed.
	at Object.dispose (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:29:4057)
	at Object.dispose (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:34:9518)
	at Uf.handleConnectionClosed (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:36:9070)
	at Uf.handleConnectionClosed (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:39:12255)
	at n (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:36:8752)
	at Tu.invoke (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:9583)
	at wr.fire (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:10348)
	at it (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:3:10845)
	at Tu.invoke (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:9583)
	at wr.fire (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:10348)
	at Mo.fireClose (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:3:523)
	at Socket.<anonymous> (/Users/aditya.kumar/.vscode/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:3:1297)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:673:12)
[Info  - 1:43:00 PM] Connection to server got closed. Server will restart.`
