### ISSUE TITLE
Plugin problem on linux

### ISSUE THREAD

**Issue by ThePepeYT** [vlang/vscode-vlang#416]
When I try to use the plugin, it works until I try to delete the "." characten then the whole server shuts down and auto completion does not work

**Comment by ThePepeYT** [comment]
Error looks like this
```Error: Connection got disposed.
	at Object.dispose (/home/bartosz/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:29:4057)
	at Object.dispose (/home/bartosz/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:34:9518)
	at Uf.handleConnectionClosed (/home/bartosz/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:36:9073)
	at Uf.handleConnectionClosed (/home/bartosz/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:39:12267)
	at n (/home/bartosz/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:36:8755)
	at Tu.invoke (/home/bartosz/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:9583)
	at wr.fire (/home/bartosz/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:10348)
	at it (/home/bartosz/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:3:10845)
	at Tu.invoke (/home/bartosz/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:9583)
	at wr.fire (/home/bartosz/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:2:10348)
	at Mo.fireClose (/home/bartosz/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:3:523)
	at Socket.<anonymous> (/home/bartosz/.vscode-oss/extensions/vlanguage.vscode-vlang-0.1.11/out/extension.js:3:1297)
	at Socket.emit (node:events:390:28)
	at Pipe.<anonymous> (node:net:687:12)
	```

**Comment by 0x9ef** [comment]
Please provide additional information to reproduce the bug.
