### ISSUE TITLE
vscode-vlang getting extension error when loading

### ISSUE THREAD

**Issue by bitmarck** [vlang/vscode-vlang#424]
Hi,

i am running vscode 1.67.0(user setup).
Adding v from the marketplace works fine but when I open a file with .v this error comes up in the Log(Extension Host)
```
[2022-05-11 08:27:18.868] [exthost] [info] ExtensionService#_doActivateExtension vlanguage.vscode-vlang, startup: false, activationEvent: 'onLanguage:v'
[2022-05-11 08:27:19.370] [exthost] [error] Activating extension vlanguage.vscode-vlang failed due to an error:
[2022-05-11 08:27:19.370] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'uri')
	at ht (c:\Users\wuser\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:39:19449)
	at ar (c:\Users\wuser\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:39:19341)
	at Object.<anonymous> (c:\Users\wuser\.vscode\extensions\vlanguage.vscode-vlang-0.1.11\out\extension.js:39:20573)
	at Module.u._compile (c:\Users\wuser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.s._load (c:\Users\wuser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:32307)
	at Function.b._load (c:\Users\wuser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:28750)
	at Function._._load (c:\Users\wuser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:61719)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.r [as __$__nodeRequire] (c:\Users\wuser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:5:101)
	at m._loadCommonJSModule (c:\Users\wuser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:102:30353)
	at m._doActivateExtension (c:\Users\wuser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:88:14751)
	at m._activateExtension (c:\Users\wuser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:88:13702)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async _activate (c:\Users\wuser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:8180)
	at async _waitForDepsThenActivate (c:\Users\wuser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:8122)
	at async _initialize (c:\Users\wuser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:7486)
```

The error in issus 194 might be a little simular but. I tried it on 2 different Windows mashines with not luck.

Any ideas would be welcomed 

Thanks a lot

**Comment by veksha** [comment]
what if you do "File-Open folder" first? (and then open .v file within that folder.)
